namespace: dev
  
replicaCount: 2

image:
  repository: docker.io/jadhav957/samplejava
  tag: latest
  pullPolicy: Always

containerPort: 8080

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: dev.testjava.infinityfreeapp.com

