name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Build the Maven project
    - name: Build with Maven
      run: mvn package -DskipTests

    # Step 4: Log in to Docker Hub (or another registry)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # Step 5: Build and tag Docker image
    - name: Build Docker Image
      run: docker build -t jadhav957/samplejava .

    # Step 6: Push Docker image to registry
    - name: Push Docker Image
      run: docker push jadhav957/samplejava
      
    # Step 7: Set up AWS credentials for accessing EKS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  
        
    # Step 8: Set up kubectl for EKS
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Step 9: Authenticate to EKS
    - name: Authenticate to EKS
      run: |
        aws eks update-kubeconfig --name os-eks-01 --region ap-south-1

    # Step 10: Setup Helm
    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    # Step 11: Deploy Helm Chart to EKS
    - name: Deploy Helm Chart
      run: |
        helm upgrade --install sample-application ./helm \
        --namespace dev \
        -f ./helm/values.yaml
